name: Hello, World!

on:
  push:
    branches:
      - develop

jobs:
  build_greeting:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env:
        first_name: Taizo
        middle_name: The
        last_name: Ito
      run: echo Hello, world! from ${first_name} ${middle_name} ${last_name}!
    - name: Run a multi-line script
      env:
        super_secret: ${{ secrets.SuperSecret }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${super_secret}
 
